### ISSUE TITLE
Feature request: suspend API calls over night

### ISSUE THREAD

**Issue by binderth** [weymann/OH3-SolarForecast-Drops#2]
Thanks for the great work on the binding. Saves me a ton of JSON fiddling! ;)

Would it be possible to define a period of no polling? So you could spare precious API calls over night, when there's no need to update information? Possible having the chance to either:

1. define a switch-item, which tells the binding to do API-Calls or suspend them
2. define Astro-binding items/channels which trigger local dusk/dawn periods?

ad 1
I could then use whatever means to turn that item ON or OFF (possibly using Astro-binding)

ad 2
I could then just use a fully configured Astro-binding to use for suspending

**Comment by weymann** [comment]
Moved into openhab addons repo as new issue
