### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by 4n4n4s** [weymann/OH3-SolarForecast-Drops#3]
Hi Bernd,
would be great if you also could publish the sources of the addon so everyone can contribute.

Thank you,
BR

**Comment by weymann** [comment]
For all bindings in openHAB Marketplace it's recommended to publish the source code. Link to code is mentioned in the [Marketplace Post](https://community.openhab.org/t/solar-forecast-pv-3-3-0-4-0-0/) 
Direct Link [here](https://github.com/weymann/openhab-addons/tree/solar-forecast/bundles/org.openhab.binding.solarforecast)
